#!/usr/bin/env bash

set -eu

DOTFILES_PATH=`realpath ~/dotfiles`
INIT_FILE=`realpath ${DOTFILES_PATH}/initialize.zsh`

if [ ! type git > /dev/null 2>&1 ];then
    echo "[Error] 'git' command not found"
    exit 1
fi

echo "Update: dotfiles"
echo "Changed current directory to ${DOTFILES_PATH}"
cd ${DOTFILES_PATH}
echo "Run: git pull"
git pull
echo "Run: setup script"
zsh ${INIT_FILE}
echo "Successfully updated: dotfiles"

echo "Update: prezto"
echo "Changed current directory to ${HOME}/.zprezto"
cd "${HOME}/.zprezto"
echo "Run: git pull and git submodule update"
git pull
git submodule update --init --recursive
echo "Successfully updated: prezto"

echo "Update: anyenv"
echo "Run: anyenv update"
anyenv update
echo "Successfully updated: anyenv"
